# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-11 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('string', models.CharField(max_length=1020)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='right_answer', to='exam.Answer')),
                ('options', models.ManyToManyField(related_name='Options_for_questions', to='exam.Answer')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('roll_no', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('branch', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=12)),
                ('city', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('sub_code', models.CharField(max_length=100)),
                ('questions', models.ManyToManyField(to='exam.Questions')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=12)),
            ],
        ),
    ]
